paths:
  input_dir: 
    present: /work/tapp/TauFF/NF4FF/Data/datasets/
    remote: /run/user/1003/gvfs/sftp:host=portal1.etp.kit.edu,user=tapp/work/tapp/TauFF/NF4FF/Data/datasets/
  output_dir:
    present: /work/tapp/TauFF/NF4FF/Data/datasets/
    remote: /run/user/1003/gvfs/sftp:host=portal1.etp.kit.edu,user=tapp/work/tapp/TauFF/NF4FF/Data/datasets/

ckpt_dir:
  present: /work/tapp/TauFF/NF4FF/results/QCD/inclusive/
  remote: /run/user/1003/gvfs/sftp:host=portal1.etp.kit.edu,user=tapp/work/tapp/TauFF/NF4FF/results/QCD/inclusive/


variables:
  - pt_vis
  - q_2
  - tau_decaymode_2
  - deltaEta_2j2
  - eta_2
  - q_1
  - deltaEta_2j1
  - deltaEta_1j2
  - mt_1
  - pt_2
  - tau_decaymode_1
  - metphi
  - eta_1
  - deltaEta_12j2
  - m_vis
  - mass_1
  - njets
  - mass_2
  - deltaR_ditaupair
  - deltaEta_12j1
  - event
  - pt_1