variables:
  - pt_1
  - pt_2
  - m_vis
  - deltaR_ditaupair
  - pt_vis
  - met
  - pt_tt
  - m_fastmtt
  # - pt_fastmtt

variables_MC:
  - pt_1
  - pt_2
  - m_vis
  - deltaR_ditaupair
  - pt_vis
  - met
  - pt_tt
  - m_fastmtt


variables_correlation:
  - pt_1
  - pt_2
  - m_vis
  - deltaR_ditaupair
  - pt_vis
  - met
  - pt_tt
  - m_fastmtt
  - mt_1
  - mt_tot

variables_correction:
  - pt_1
  - pt_2
  - m_vis
  - deltaR_ditaupair
  - pt_vis
  - met
  - pt_tt
  - m_fastmtt
  - mt_1
  - mt_tot