variables: /work/tapp/TauFF/NF4FF/Normalizing_Flow_tt/configs/training_variables.yaml
config_NF: /work/tapp/TauFF/NF4FF/Normalizing_Flow_tt/configs/config_NF.yaml
datasets: /work/tapp/TauFF/NF4FF/Data/datasets/
NF_results: /work/tapp/TauFF/NF4FF/Normalizing_Flow_tt/NF_results
config_settings: /work/tapp/TauFF/NF4FF/Classifier_tt/configs/config_settings.yaml
labels: /work/tapp/TauFF/NF4FF/Normalizing_Flow_tt/configs/labels.yaml
labels_short: /work/tapp/TauFF/NF4FF/Normalizing_Flow_tt/configs/labels_short.yaml
plots: /work/tapp/TauFF/NF4FF/Normalizing_Flow_tt/plots
process_map:
  no_embedding: /work/tapp/TauFF/NF4FF/Classifier_tt/configs/data_process_mapping_no_embedding.yaml
  embedding: /work/tapp/TauFF/NF4FF/Classifier_tt/configs/data_process_mapping_embedding.yaml