model:
  hidden_nodes: [100, 100, 100, 100] 
  output_nodes: 1
  activation: ReLU
  output_activation: Sigmoid
  dropout: 0.10

training:
  epochs: 500
  lr: 0.002

scheduler:
  patience: 20
  early_stopping_patience: 1000
  factor: 0.1
  min_delta: 1.0e-4
  min_lr: 1.0e-7