masks:
  preselection:
    - eta_1 <= 2.3
    - eta_2 <= 2.3
    - pt_1 >= 40
    - pt_2 >= 40
    - (tau_decaymode_2 == 0) | (tau_decaymode_2 == 1) | (tau_decaymode_2 == 10) | (tau_decaymode_2 == 11)


  # Determination Region
  DR:
    - q_1 * q_2 > 0
    - extramuon_veto < 0.5
    - extraelec_veto < 0.5
    - id_tau_vsJet_VLoose_1 > 0.5
    - id_tau_vsJet_VLoose_2 > 0.5

  AR_like_tau1:  
    - id_tau_vsJet_VLoose_1 > 0.5
    - id_tau_vsJet_Tight_1 < 0.5
    - id_tau_vsJet_Tight_2 > 0.5
    - q_1 * q_2 > 0
    - extramuon_veto < 0.5
    - extraelec_veto < 0.5
    - process == 0

  AR_like_tau2:
    - id_tau_vsJet_VLoose_2 > 0.5
    - id_tau_vsJet_Tight_2 < 0.5
    - id_tau_vsJet_Tight_1 > 0.5
    - q_1 * q_2 > 0
    - extramuon_veto < 0.5
    - extraelec_veto < 0.5
    - process == 0

  SR_like:
    - id_tau_vsJet_Tight_1 > 0.5
    - id_tau_vsJet_Tight_2 > 0.5
    - q_1 * q_2 > 0
    - extramuon_veto < 0.5
    - extraelec_veto < 0.5
    - process == 0

  # Anti-Determination Region
  SR:
    - id_tau_vsJet_Tight_1 > 0.5
    - id_tau_vsJet_Tight_2 > 0.5
    - (q_1*q_2) < 0
    - extramuon_veto < 0.5
    - extraelec_veto < 0.5

  AR_tau1:
    - id_tau_vsJet_VLoose_1 > 0.5
    - id_tau_vsJet_Tight_1 < 0.5
    - id_tau_vsJet_Tight_2 > 0.5
    - (q_1*q_2) < 0
    - extramuon_veto < 0.5
    - extraelec_veto < 0.5
    
  AR_tau2:
    - id_tau_vsJet_VLoose_2 > 0.5
    - id_tau_vsJet_Tight_2 < 0.5
    - id_tau_vsJet_Tight_1 > 0.5
    - (q_1*q_2) < 0
    - extramuon_veto < 0.5
    - extraelec_veto < 0.5
